### PR TITLE
Brew audit fixes.

### PR DESCRIPTION
**Pull request by David-Engel**
Merging fixes from PR #5 and applying brew audit fixes to other scripts as well.

### CODE REVIEW

**Comment by David-Engel** [comment]
@v-sutso Can you double-check my work? (Not urgent, prioritize behind existing release tasks.) Thanks!

**Comment by David-Engel** [comment]
@v-sutso I removed the version line because brew audit returns this when it is there:
`Stable: version 13.1.9.0 is redundant with version scanned from URL`
It seems brew will still recognize the appropriate version even without it explicitly defined using `version`. If you still prefer, I will add the line back in and we will just live with the audit error.

**Comment by v-sutso** [comment]
I think we should leave it there.

**Comment by David-Engel** [comment]
@v-sutso I added `version` back in.

**Pull request merged**
